esphome:
  name: aveo
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #Optional manual IP
  manual_ip:
    static_ip: 10.117.3.106
    gateway: 10.117.3.1
    subnet: 255.255.255.0
  fast_connect: on
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid:  !secret wifi_fallback_ap
    password: !secret wifi_fallback_password
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

mqtt:
  broker: 10.117.2.102
  username: !secret mqtt_id
  password: !secret mqtt_password
  birth_message:
    topic: homeassistant/binary_sensor/aveo/state
    payload: "ON"
  will_message:
    topic: homeassistant/binary_sensor/aveo/state
    payload: "OFF"
    
#  on_message:
#     - topic: homeassistant/binary_sensor/smart/state
#       payload: "ON"
#       then:
#        - mqtt.publish:
#            topic: zanzito/oneplus5/say
#            payload: "Welcome home"
sensor:
  - platform: wifi_signal
    name: "Aveo WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Aveo Uptime"