substitutions:
  esphome_name: esp32_web_cam

esphome:
  name: ${esphome_name}
  platform: ESP32
  board: esp-wrover-kit

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: ${esphome_name}
  # ...

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #Optional manual IP

  manual_ip:
    static_ip: 10.117.3.105
    gateway: 10.117.3.1
    subnet: 255.255.255.0
  fast_connect: on
  ap:
   ssid:  !secret wifi_fallback_ap
   password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password


web_server:
  port: 80
  
time:
  - platform: homeassistant
 