substitutions:
  esphome_name: menize_room

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #Optional manual IP
  manual_ip:
    static_ip: 10.117.3.102
    gateway: 10.117.3.1
    subnet: 255.255.255.0
  fast_connect: on
  ap:
   ssid:  !secret wifi_fallback_ap
   password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

sensor:
  - platform: dht
    pin: D7
    model: dht22
    temperature:
      name: "${esphome_name} temperature"
    humidity:
      name: "${esphome_name} humidity"
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin: D6
    name: "${esphome_name} motion"
    device_class: motion

#light:
#  - platform: fastled_clockless
#    chipset: WS2811
#    pin: D3
#    num_leds: 1
#    rgb_order: RGB
#    name: "Wonder FastLED"

web_server:
  port: 80
  
time:
  - platform: homeassistant
 